### model
model_name_or_path: /workspace/mnt/cmss-wangdepeng/cpt/qwen-ckpts/tinyllama-v1.0-1T

### method
stage: pt
do_train: true
finetuning_type: full
lora_target: all

### dataset
dataset: starcoder_raw
streaming: true
max_steps: 1000000
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 192

### output
output_dir: /workspace/mnt/cmss-wangdepeng/cpt/qwen-ckpts/tinyllama-v1.0-1T-starcoder-1008
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 4.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_steps: 2000
bf16: true
ddp_timeout: 180000000
weight_decay: 0.1