### model
model_name_or_path: /workspace/mnt/cmss-hewu/model_zoo/chatcm-57bv1-base-hf

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: starcoder
cutoff_len: 1024
streaming: true
max_steps: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../../checkpoint/jiutian-57b/full/pretrain
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 1024
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
